version: '3'
services:
  postgres:
    image: 'postgres:13'
    container_name: 'postgres_db'
    environment:
      POSTGRES_USER='postgres'
      POSTGRES_PASSWORD='postgres'
      POSTGRES_DB='postgres'
    ports:
      -"5432:5432"
    volumes:
      -postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network
  
  # for the services communicating with each other they 
  # must be on same network and below coomand make a network
  # if it doen't exist
  networks:
    airflow_network:
      external: false
  
  # This comand make an volume if it doen't exist
  volumes:
    postgres_data:
